traducao: security-basic-authentication-howto.adoc.po
quarkusio/pt.quarkus.io pull request #17
Opened 2023-09-27 01:54 UTC by Renata00000

Hello everyone, I kindly request a review.
fixed #16

2023-09-27 02:47 UTC, gastaldi requested changes
Found some minor typos, but looks good overall, good job!

2023-09-27 02:47 UTC, gastaldi commented on l10n/po/pt_BR/_guides/security-basic-authentication-howto.adoc.po
> +msgstr "Active  link:security-basic-authentication.html[a autenticação básica] para o seu projeto Quarkus e permita que os usuários se autentiquem com um use rname e um password."
```suggestion
msgstr "Ative link:security-basic-authentication.html[a autenticação básica] para o seu projeto Quarkus e permita que os usuários se autentiquem com um username e um password."
```

2023-09-27 02:47 UTC, gastaldi commented on l10n/po/pt_BR/_guides/security-basic-authentication-howto.adoc.po
> +msgstr "Você Instalou pelo menos uma extensão que fornece um `IdentityProvider` baseado no usename e no password, como o  link:security-jdbc.html[Elytron JDBC]."
```suggestion
msgstr "Você instalou pelo menos uma extensão que fornece um `IdentityProvider` baseado no usename e no password, como o  link:security-jdbc.html[Elytron JDBC]."
```

2023-09-27 02:47 UTC, gastaldi commented on l10n/po/pt_BR/_guides/security-basic-authentication-howto.adoc.po
> +msgstr "A configuração de nomes de username, secrets e roles no arquivo `application.properties` só é adequada para cenários de teste. Se estiver protegerndo uma aplicação em produção, utilize sempre
```suggestion
msgstr "A configuração de nomes de username, secrets e roles no arquivo `application.properties` só é adequada para cenários de teste. Se estiver protegendo uma aplicação em produção, utilize sempre uma base de dados para armazenar estas informações."
```

2023-09-27 02:47 UTC, gastaldi commented on l10n/po/pt_BR/_guides/security-basic-authentication-howto.adoc.po
> +msgstr "Para obter um guia mais detalhado que mostra como configurar a autenticação básica juntamente com o Jakarta Persistence para armazenar credenciais de utilizador numa base de dados, consulte o
```suggestion
msgstr "Para obter um guia mais detalhado que mostra como configurar a autenticação básica juntamente com o Jakarta Persistence para armazenar credenciais de usuário numa base de dados, consulte o guia  link:security-basic-authentication-tutorial.html[Proteger uma aplicação Quarkus com autenticação básica e o Jakarta Persistence]."
```

2023-09-27 02:47 UTC, gastaldi commented on l10n/po/pt_BR/_guides/security-basic-authentication-howto.adoc.po
> +msgstr "link:security-testing.html#configuring-user-information[Configurar as informações do usuario no application.properties]"
```suggestion
msgstr "link:security-testing.html#configuring-user-information[Configurar as informações do usuário no application.properties]"
```

2023-09-27 02:49 UTC, gastaldi commented
Don't forget to review *all* entries and remove the `fuzzy` keyword above the msgid (disable the `Needs Some Work` toggle in Poedit) when it's ready

2023-09-27 20:34 UTC, Renata00000 commented
TKS George!

2023-09-28 11:19 UTC, gastaldi approved these changes

2023-09-28 12:25 UTC, merged