#239 Translation: doc-create-tutorial.adoc.po
quarkusio/pt.quarkus.io pull request #240
Opened 2024-10-17 04:57 UTC by luizpais

Translation of doc-create-tutorial.adoc.po file.

2024-10-17 10:18 UTC, gastaldi commented on l10n/po/pt_BR/_guides/doc-create-tutorial.adoc.po
> +msgstr "Tenha à mão as  link:doc-reference.html[directrizes de estilo e conteúdo do Quarkus] como referência para a sintaxe necessária e outras convenções."
```suggestion
msgstr "Tenha à mão as  link:doc-reference.html[diretrizes de estilo e conteúdo do Quarkus] como referência para a sintaxe necessária e outras convenções."
```

2024-10-17 10:19 UTC, gastaldi commented on l10n/po/pt_BR/_guides/doc-create-tutorial.adoc.po
> +#: upstream/_guides/doc-create-tutorial.adoc:23
Deixe do jeito que está. Melhorias devem ser feitas no repositório original primeiro (https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/doc-create-tutorial.adoc)

```suggestion
#: _guides/doc-create-tutorial.adoc
```

2024-10-17 10:22 UTC, gastaldi requested changes
O arquivo não pode ter a referencia a `upstream/_guides/doc-create-tutorial.adoc`. Somente as `msgstr` devem ser alteradas: por exemplo: https://github.com/quarkusio/pt.quarkus.io/pull/227/files

2024-10-18 21:19 UTC, luizpais commented on l10n/po/pt_BR/_guides/doc-create-tutorial.adoc.po
> +#: upstream/_guides/doc-create-tutorial.adoc:23
Estranho. A princípio utilizei o PoEdit para traduzir. Vou tomar cuidado com os Ctrl+H. 
Obrigado @gastaldi

2024-10-18 21:58 UTC, closed without merging